spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mybatis
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jwat.API_Mybatis.model

jwt:
  secret: ${SECRET_KEY}
  access-expiration-ms: 600000 # 10 minutes
  refresh-expiration-ms: 1209600000 # 14 days

