spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mybatis
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jwat.API_Mybatis.model
